### ISSUE TITLE
Crash when loaded with CCSE

### ISSUE THREAD

**Issue by whitehat101** [CookieMonsterTeam/CookieMonster#834]
I looked at https://github.com/CookieMonsterTeam/CookieMonster/issues/332 but it didn't lead me to a solution.

**Describe the bug**
I'm trying to use CookieMonster in combination with CCSE's FortuneCookie. In the past both mods worked together, but in my recent revival, I've had issues. I've started looking into it, and have come up with a custom loader. Both mods are patching `Game.UpdateSpecial` in a load order dependent way.

**To Reproduce**
On any save, even a fresh one:
```javascript
Game.LoadMod('https://klattmose.github.io/CookieClicker/CCSE.js')
Game.LoadMod('https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js')
```
I was originally loading `FortuneCookie.js` instead of `CCSE.js`, but just CCSE reproduces it more minimally. 

Console Errors:
```
VM50102:1 Uncaught ReferenceError: ei is not defined
    at Object.Game.UpdateSpecial (eval at CCSE.ReplaceCodeIntoFunction (CCSE.js:231), <anonymous>:1:33)
    at Object.Game.Logic (main.js?v=2.089:13814)
    at Object.Game.Logic (ReplaceNative.js:134)
    at Game.Loop (main.js?v=2.089:14394)
```
Animation halts, the game is unplayable.

**Browser**
Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Investigation**

The variable `ei` is a result of minification. CCSE is trying to patch the following code: 
```javascript
Game.UpdateSpecial = function(){ei(T.UpdateSpecial)}
```
With source maps, I see this was:
```javascript
BackupFunctions.UpdateSpecial = Game.UpdateSpecial;
Game.UpdateSpecial = function () {
  FixMouseY(BackupFunctions.UpdateSpecial);
};
```
But since `FixMouseY` and `BackupFunctions` are only available inside a closure, CCSE would fail even without minification.

CCSE used a more advanced code patching technique that stringifies a function, and inserts new statements after specific points, and re-evaluates the function. CookieMonster captures the original function in ` BackupFunctions.UpdateSpecial`, and then replaces `Game.UpdateSpecial` with new code that calls the backup function.

The way CCSE uses `CCSE.ReplaceCodeIntoFunction` is pretty neat, it might be worthwhile to adopt a similar approach.

**Workaround**

Wait until `CCSE.isLoaded` is truthy, then load Cookie Monster.

I use a custom Web Extension to load mods and other tweaks. The relevant part of my loader now looks like:

```javascript
setTimeout(function waitForGame() {
  if (typeof Game === 'object' && Game.ready) {
    Game.LoadMod('https://klattmose.github.io/CookieClicker/FortuneCookie.js')
    setTimeout(function waitForCCSE() {
      if (typeof CCSE === 'object' && CCSE.isLoaded)
        Game.LoadMod('https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js')
      else setTimeout(waitForCCSE)
    })
  } else setTimeout(waitForGame)
})
```

I'm thinking adopting a CCSE-style of patching would be the most compatible, since it mimics and takes advantage of the closure-less coding style of the base game, and it allows more precise code injection than wrapping with closures. Otherwise, users are probably going to have to come up their own loaders, like I did, to help encourage a sane load order.

If CCSE adopted CookieMonster's wrapping style, mod load order would still be an issue (should CCSE wrap CookieMonster, or should CookieMonster wrap CCSE?), and modders would only be able to add code before or after the base game's code, not at any arbitrary point.

**Comment by DanielNoord** [comment]
We used a similar wrapping style as CCSE but removed it as `eval` is generally frowned upon by most programmers and linters. However, as long as Orteil does not provide a full fledged modding framework we might need to once again resort to this.

I am thinking of waiting for the next update for the base game (there have been some tweets by Orteil that he is working on one) to see if anything changes and if not revert to the old wrapping style.

**Comment by EpicPuppy613** [comment]
Encountering this same issue whenever loading both CM and any mod that uses CCSE, tried changing mod loading order, loading CCSE itself first, etc.

Using CCMM, idk if that changes anything

Depending on what order mods are loaded in different errors come up:
- CM first: ```Uncaught ReferenceError: Kt is not defined
    at Object.Game.tooltip.draw (eval at CCSE.SliceCodeIntoFunction (CCSE.js?v=1644281548446:219:3), <anonymous>:1:37)
    at HTMLDivElement.l.onmouseover.l.onmouseover (Tooltips.js:18:22)```
- CM last works but menus don't show CM options: ```Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.eval [as UpdateMenu] (eval at inject (webpack-internal:///39), <anonymous>:338:12)
    at Object.Game.UpdateMenu (https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js?v=1644281661511:2:190392)
    at Object.Game.ShowMenu (https://orteil.dashnet.org/cookieclicker/main.js?v=2.091:5709:9)
    at HTMLDivElement.<anonymous> (https://orteil.dashnet.org/cookieclicker/main.js?v=2.091:6103:53)```
- Sometimes menus just don't work: ```Uncaught ReferenceError: s is not defined
    at Object.eval [as UpdateMenu] (eval at inject (39:1:1), <anonymous>:4:20)
    at Object.Game.Logic (main.js?v=2.091:14229:105)
    at Object.Game.Logic (ReplaceNative.js:134:21)
    at Game.Loop (main.js?v=2.091:14395:8)```
